sudo: required
dist: trusty
language: node_js
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install && npm update
- bower install && bower update
script:
- xvfb-run -a wct
