sudo: required
dist: trusty
language: node_js
node_js:
- 4.4.7
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install
- npm update
- bower install
script:
- xvfb-run -a wct --skip-selenium-install
